teambuilding/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (CreateProfileView, DetailProfileView, 
                    LogInView, LogOutView, SignUp, UpdateProfileView)


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUp.as_view(), name="signup"),
    path('login/', LogInView.as_view(), name="login"),
    path('logout/', LogOutView.as_view(), name="logout"),
    path('profile/create/', CreateProfileView.as_view(), name="profile-create"),
    path('profile/detail/<slug:slug>/', DetailProfileView.as_view(), name="profile-detail"),
    path('profile/update/<slug:slug>/', UpdateProfileView.as_view(), name="profile-update"),
]

teambuilding/projects/urls.py
from django.urls import path

from .views import CreateApplicantView, CreateProjectView, DeleteProjectView, DetailProjectView, ListApplicationsView, UpdateApplicantView, UpdateProjectView


app_name = 'projects'
urlpatterns = [
    path('project/create/', CreateProjectView.as_view(), name='project-create'),
    path('project/detail/<slug:slug>/', DetailProjectView.as_view(), name='project-detail'),
    path('project/update/<slug:slug>/', UpdateProjectView.as_view(), name='project-update'),
    path('project/delete/<slug:slug>/', DeleteProjectView.as_view(), name='project-delete'),
    path('project/apply/<slug:slug>/<int:pk>/', CreateApplicantView.as_view(), name='applicant-create'),
    path('project/applicant/update/<int:pk>/', UpdateApplicantView.as_view(), name='applicant-update'),
    path('applications/', ListApplicationsView.as_view(), name="applications-list"),
]

teambuilding/teambuilding/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from .views import Home, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('search_result/', Search.as_view(), name="search-results"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

teambuilding/templates/index.html
{% extends 'layout.html' %}
{% block content %}
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Projects</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="{% url 'projects:project-create' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <form method="GET">
          <select name="filter">
            <option>All Needs</option>
            <option>Android Developer</option>
            <option>Designer</option>
            <option>IOS Developer</option>
            <option>Java Developer</option>
            <option>Other</option>
            <option>PHP Developer</option>
            <option>Python Developer</option>
            <option>Rails Developer</option>
            <option>WordPress Developer</option>
          </select>
          <p><input type="submit" name="submit" value="submit"/></p>
        </form>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
        {% if object_list %}
          {% for project in object_list %}
            <tr class="clickable-row" data-href="{% url 'projects:project-detail' slug=project.slug %}">
              <td>
                <h3>{{ project }}</h3>
              </td>
              <td class="circle--cell--right">
              {% for needs in project.position.all %}
                {% if not needs.position_filled %}
                  <span class="secondary-label">{{ needs }}</span>
                {% endif %}
              {% endfor %}
              </td>
            </tr>
          {% endfor %}
        {% endif %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

teambuilding/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Circle</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'css/global.css' %}">

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/global.js' %}"></script>

</head>

<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
          <form action="{% url 'search-results' %}" method="GET">
            <input name="q" type="text" placeholder="Search...">
          </form>
              <button>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
              </button>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
            {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
              {% if user.profile %}
                <li><a href="{% url 'accounts:profile-detail' slug=user.profile.slug %}">Profile</a></li>
              {% endif %}
            {% else %}
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
{% block content %}{% endblock %}
</body>
</html>

teambuilding/templates/search.html
{% {% extends 'layout.html' %}%}
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="index.html">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <input type="text" placeholder="Search Projects..." value="sass" />
            <button>
              <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
            </button>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              <li><a href="signup.html">Sign Up</a></li>
              <li><a href="signin.html">Sign In</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Search</h2>
        <p>Search research for: <span class="secondary-label">sass</span></p>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="project_new.html">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Needs</a></li>
          <li><a>Android Developer</a></li>
          <li><a>Designer</a></li>
          <li><a>Java Developer</a></li>
          <li><a>PHP Developer</a></li>
          <li><a>Python Developer</a></li>
          <li><a>Rails Developer</a></li>
          <li><a>WordPress Developer</a></li>
          <li><a>iOS Developer</a></li>
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Invoice Delivery Tool</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Rails Developer</span>
            </td>
          </tr>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Twitter Client</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Designer</span>
            </td>
          </tr>
        </tbody>
      </table>

    </div>

  </div>
</body>
</html>

teambuilding/templates/search_result.html
{% extends 'layout.html' %}
{% block content %}
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Search</h2>
        <p>Search research for:
          <span class="secondary-label">
            {{ q }}
          </span></p>
        
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="{% url 'projects:project-create' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          {% if project_list %}
          {% for project in project_list %}
            <tr class="clickable-row" data-href="{% url 'projects:project-detail' slug=project.slug %}">
              <td>
                <h3>{{ project }}</h3>
              </td>
              <td class="circle--cell--right">
              {% for needs in project.position.all %}
                {% if not needs.position_filled %}
                  <span class="secondary-label">{{ needs }}</span>
                {% endif %}
              {% endfor %}
              </td>
            </tr>
          {% endfor %}
        {% endif %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}