teambuilding/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (CreateProfileView, DetailProfileView, 
                    LogInView, LogOutView, SignUp, UpdateProfileView)


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUp.as_view(), name="signup"),
    path('login/', LogInView.as_view(), name="login"),
    path('logout/', LogOutView.as_view(), name="logout"),
    path('profile/create/', CreateProfileView.as_view(), name="profile-create"),
    path('profile/detail/<slug:slug>/', DetailProfileView.as_view(), name="profile-detail"),
    path('profile/update/<slug:slug>/', UpdateProfileView.as_view(), name="profile-update"),
]

teambuilding/projects/urls.py
from django.urls import path

from .views import CreateApplicantView, CreateProjectView, DeleteProjectView, DetailProjectView, ListApplicationsView, UpdateApplicantView, UpdateProjectView


app_name = 'projects'
urlpatterns = [
    path('project/create/', CreateProjectView.as_view(), name='project-create'),
    path('project/detail/<slug:slug>/', DetailProjectView.as_view(), name='project-detail'),
    path('project/update/<slug:slug>/', UpdateProjectView.as_view(), name='project-update'),
    path('project/delete/<slug:slug>/', DeleteProjectView.as_view(), name='project-delete'),
    path('project/apply/<slug:slug>/<int:pk>/', CreateApplicantView.as_view(), name='applicant-create'),
    path('project/applicant/update/<int:pk>/', UpdateApplicantView.as_view(), name='applicant-update'),
    path('applications/', ListApplicationsView.as_view(), name="applications-list"),
]

teambuilding/teambuilding/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from .views import Home, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('search_result/', Search.as_view(), name="search-results"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

teambuilding/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from projects.models import Position


class UserManager(BaseUserManager):
    """Defines a model manager for User model with no username field."""

    def create_user(self, email, password):
        if not email:
            raise ValueError("Email is required.")
        email = self.normalize_email(email)
        user = self.model(
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    
class User(AbstractUser):
    """New User model."""
    username = None
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
        )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE,
        related_name="profile"
        )
    slug = models.SlugField(allow_unicode=True, unique=True)
    name = models.CharField(max_length=60)
    description = models.TextField()
    profile_picture = models.ImageField(
        upload_to="profile_picture", 
        default='profile_picture/default_pic.jpg'
        )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        email = self.user.email.split("@", 1)
        self.slug = slugify(email[0])
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("accounts:profile-detail", kwargs={"slug": self.slug})


class Skill(models.Model):
    profile = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE,
        related_name="skill"
        )
    skills = models.CharField(
        max_length=3,
        choices=Position.POSITION_CHOICES
        )

    def __str__(self):
        return self.get_skills_display()


class MyProject(models.Model):
    profile = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE,
        related_name="myproject"
        )
    title = models.CharField(max_length=60, blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

teambuilding/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import inlineformset_factory

from .models import MyProject, Profile, Skill


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Email'})
        )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
        )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})
        )

    class Meta:
        fields = ("email", "password1", "password2")
        model = get_user_model()

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'name',
            'description',
            'profile_picture'
        ]
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Full Name',
                'class': 'circle--input--h1'
                }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Tell us about yourself...',
                'rows': 5
                })
        }


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = [
            'skills'
        ]


class MyProjectForm(forms.ModelForm):
    class Meta:
        model = MyProject
        fields = [
            'title',
            'url'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Project Name'}),
            'url': forms.URLInput(attrs={'placeholder': 'Project Url'})
        }

SkillInlineFormSet = inlineformset_factory(
    Profile, 
    Skill,
    extra=2,
    fields=('skills',),
    form=SkillForm,
    min_num=1,
    )

MyProjectInlineFormSet = inlineformset_factory(
    Profile,
    MyProject,
    extra=2,
    fields=('title', 'url'),
    form=MyProjectForm
)

teambuilding/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView, UpdateView

from .forms import (MyProjectInlineFormSet, ProfileForm, 
                    SkillInlineFormSet, UserCreateForm)
from .models import Profile


class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("accounts:profile-create")
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        valid = super(SignUp, self).form_valid(form)
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")
        new_user = authenticate(email=email, password=password)
        login(self.request, new_user)
        return valid


class LogInView(FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy("home")
    template_name = "accounts/login.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


class LogOutView(RedirectView):
    url = reverse_lazy("home")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class CreateProfileView(LoginRequiredMixin, CreateView):
    form_class = ProfileForm
    template_name = "accounts/profile_form.html"
    model = Profile

    def get_context_data(self, **kwargs):
        context = super(CreateProfileView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["skills_formset"] = SkillInlineFormSet(self.request.POST)
            context["my_project_formset"] = MyProjectInlineFormSet(
                self.request.POST
                )
        else:
            context["skills_formset"] = SkillInlineFormSet()
            context["my_project_formset"] = MyProjectInlineFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        skills = context["skills_formset"]
        my_projects = context["my_project_formset"]
        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
        if skills.is_valid() and my_projects.is_valid():
            skills.instance = self.object
            skills.save()
            my_projects.instance = self.object
            my_projects.save()
        return super(CreateProfileView, self).form_valid(form)


class DetailProfileView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "accounts/profile_detail.html"


class UpdateProfileView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = ProfileForm
    template_name = "accounts/profile_form.html"
    model = Profile

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user

    def get_context_data(self, **kwargs):
        context = super(UpdateProfileView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["skills_formset"] = SkillInlineFormSet(
                self.request.POST, instance=self.object
                )
            context["my_project_formset"] = MyProjectInlineFormSet(
                self.request.POST, instance=self.object
                )
        else:
            context["skills_formset"] = SkillInlineFormSet(
                instance=self.object
                )
            context["my_project_formset"] = MyProjectInlineFormSet(
                instance=self.object
                )
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        skills = context["skills_formset"]
        my_projects = context["my_project_formset"]
        self.object = form.save()
        if skills.is_valid() and my_projects.is_valid():
            skills.instance = self.object
            skills.save()
            my_projects.instance = self.object
            my_projects.save()
        return super(UpdateProfileView, self).form_valid(form)

teambuilding/accounts/templates/accounts/login.html
{% extends 'layout.html' %}
{% block content %}
<div class="bounds">
  <div class="grid-30 centered">
    <h2>Sign In</h2>
    <form method="POST">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="button-primary" value="Log In">
    </form>
  </div>
</div>
{% endblock %}

teambuilding/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Circle</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="../../css/global.css">

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="../../js/autogrow.js"></script>
  <script type="text/javascript" src="../../js/global.js"></script>


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="index.html">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <input type="text" placeholder="Search Projects..." />
            <button>
              <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
            </button>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              <li><a href="signup.html">Sign Up</a></li>
              <li><a href="signin.html">Sign In</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="applications.html">Applications</a></li>
        <li><a class="selected" href="profile.html">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button icon-on-left" href="profile_edit.html">Edit</a>
      </div>
    </div>

    <div class="grid-70">
      <h1>Wendy McElroy</h1>
      <div class="circle--article--body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>

      <h2>Past Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Invoice Delivery Tool</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Rails Developer</span>
            </td>
          </tr>
          <tr class="clickable-row" data-href="project.html">
            <td>
              <h3>Twitter Client</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Designer</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <div class="circle--primary--avatar">

        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="unloaded">
          <li>Skill 1</li>
          <li>Skill 2</li>
          <li>Skill 3</li>
          <li>Skill 4</li>
          <li>Skill 5</li>
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--link--list">
          <li><a>Project 1</a></li>
          <li><a>Project 2</a></li>
          <li><a>Project 3</a></li>
          <li><a>Project 4</a></li>
        </ul>
      </div>
    </div>

  </div>
</body>
</html>

teambuilding/accounts/templates/accounts/profile_detail.html
{% extends 'layout.html' %}

{% block content %}

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:applications-list' %}">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile-detail' slug=profile.slug %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
      {% if user == profile.user %}
        <a class="button icon-on-left" href="{% url 'accounts:profile-update' slug=profile.slug %}">Edit</a>
      {% endif %}
      </div>
    </div>

    <div class="grid-70">
      <h1>{{ profile.name }}</h1>
      <div class="circle--article--body">
        <p>{{ profile.description|linebreaks }}</p>

        
      </div>

      <h2>Past Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          {% if user.project %}
            {% for project in user.project.all %}
              <tr class="clickable-row" data-href="{% url 'projects:project-detail' slug=project.slug %}">
                <td>
                  <h3>{{ project.title }}</h3>
                </td>
                <td class="circle--cell--right">
                  {% for needs in project.position.all %}
                    <span class="secondary-label">{{ needs }}</span>
                  {% endfor %}
                </td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
          <img class="circle--primary--avatar" src="{{ profile.profile_picture.url }}">
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="unloaded">
        {% for skill in profile.skill.all %}
          <li>{{ skill }}</li>
        {% endfor %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--link--list">
        {% for my_project in profile.myproject.all %}
          <li><a href={{my_project.url}} target="_blank">{{ my_project.title }}</a></li>
        {% endfor %}
        </ul>
      </div>
    </div>

  </div>
{% endblock %}

teambuilding/accounts/templates/accounts/profile_form.html
{% extends 'layout.html' %}

{% block content %}

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:applications-list' %}">Applications</a></li>
        {% if user.profile %}
          <li><a class="selected" href="{% url 'accounts:profile-detail' slug=profile.slug %}">Profile</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>


  <div class="bounds circle--page">
    <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
      <div class="circle--page--header circle--fluid">
        <div class="circle--fluid--cell circle--fluid--primary">
          <h2>Profile</h2>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <input type="submit" class="button button-primary icon-on-left" value="Save Changes">
        </div>
      </div>

      <div class="grid-70">
        {{ form.name }}
        <div class="circle--article--body">
          {{ form.description }}
        </div>

        <h2>Past Projects</h2>
        <table class="u-full-width circle--table">
          <thead>
            <tr>
              <th>Project Title</th>
              <th class="circle--cell--right">Project Needs</th>
            </tr>
          </thead>
          <tbody>
            {% if user.project %}
              {% for project in user.project.all %}
                <tr class="clickable-row" data-href="{% url 'projects:project-detail' slug=project.slug %}">
                  <td>
                    <h3>{{ project.title }}</h3>
                  </td>
                  <td class="circle--cell--right">
                    {% for needs in project.position.all %}
                      <span class="secondary-label">{{ needs }}</span>
                    {% endfor %}
                  </td>
                </tr>
              {% endfor %}
            {% endif %}
          </tbody>
        </table>
      </div>

      <div class="grid-25 grid-push-5">

        <div class="circle--secondary--module">
          <div class="circle--primary--avatar">
            <a class="button">
              Upload Photo
              <input name="profile_picture" type="file">
            </a>
          </div>
        </div>

        <div class="circle--secondary--module">
        
          <h4>My Skills</h4>
          {{ skills_formset.management_form }}
          <ul class="circle--clone--list">
            {% for skill in skills_formset%}
              {{ skill.id }}
              <li>{{ skill }}</li>
            {% endfor %}
          </ul>
          
        </div>

        <div class="circle--secondary--module">
          <h4>My Projects</h4>
          {{ my_project_formset.management_form }}
          {% for my_project in my_project_formset%}
            {{ my_project.id }}
            <ul class="circle--clone--list">
             <li>{{ my_project.title }}</li>
             <li>{{ my_project.url }}</li>
            </ul>
          {% endfor %}
        </div>
      </div>
    </form>
  </div>

{% endblock %}

teambuilding/accounts/templates/accounts/signin.html
{% extends 'layout.html' %}
{% block content %}
<div class="bounds">
  <div class="grid-30 centered">
    <h2>Sign In</h2>
    <form method="POST">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="button-primary" value="Sign In">
    </form>
  </div>
</div>
{% endblock %}

teambuilding/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}
{% block content %}
  <div class="bounds">
    <div class="grid-30 centered">
      <h2>Sign Up</h2>
      <form method="POST">
      {% csrf_token %}
        {{ form.email.errors }}
        {{ form.email }}
        {{ form.password1.errors }}
        {{ form.password1 }}
        {{ form.password2.errors }}
        {{ form.password2 }}
        <input type="submit" class="button-primary" value="Sign Up">
      </form>
    </div>
  </div>
{% endblock %}