teambuilding/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (CreateProfileView, DetailProfileView, 
                    LogInView, LogOutView, SignUp, UpdateProfileView)


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUp.as_view(), name="signup"),
    path('login/', LogInView.as_view(), name="login"),
    path('logout/', LogOutView.as_view(), name="logout"),
    path('profile/create/', CreateProfileView.as_view(), name="profile-create"),
    path('profile/detail/<slug:slug>/', DetailProfileView.as_view(), name="profile-detail"),
    path('profile/update/<slug:slug>/', UpdateProfileView.as_view(), name="profile-update"),
]

teambuilding/projects/urls.py
from django.urls import path

from .views import CreateApplicantView, CreateProjectView, DeleteProjectView, DetailProjectView, ListApplicationsView, UpdateApplicantView, UpdateProjectView


app_name = 'projects'
urlpatterns = [
    path('project/create/', CreateProjectView.as_view(), name='project-create'),
    path('project/detail/<slug:slug>/', DetailProjectView.as_view(), name='project-detail'),
    path('project/update/<slug:slug>/', UpdateProjectView.as_view(), name='project-update'),
    path('project/delete/<slug:slug>/', DeleteProjectView.as_view(), name='project-delete'),
    path('project/apply/<slug:slug>/<int:pk>/', CreateApplicantView.as_view(), name='applicant-create'),
    path('project/applicant/update/<int:pk>/', UpdateApplicantView.as_view(), name='applicant-update'),
    path('applications/', ListApplicationsView.as_view(), name="applications-list"),
]

teambuilding/teambuilding/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from .views import Home, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('search_result/', Search.as_view(), name="search-results"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

teambuilding/projects/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Project(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(allow_unicode=True)
    project_owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
        related_name="project"
        )
    description = models.TextField()
    timeline = models.TextField()
    applicant_requirements = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("projects:project-detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-created_at']
    

class Position(models.Model):
    ANDROID_DEVELOPER = 'AND'
    DESIGNER = 'DES'
    IOS_DEVELOPER = 'IOS'
    JAVA_DEVELOPER = 'JAV'
    PHP_DEVELOPER = 'PHP'
    PYTHON_DEVELOPER = 'PYT'
    RAILS_DEVELOPER = 'RAI'
    WORDPRESS_DEVELOPER = 'WOR'
    OTHER = 'OTH'

    POSITION_CHOICES = [
    (ANDROID_DEVELOPER, 'Android Developer'),
    (DESIGNER, 'Designer'),
    (IOS_DEVELOPER, 'IOS Developer'),
    (JAVA_DEVELOPER, 'Java Developer'),
    (PHP_DEVELOPER, 'PHP Developer'),
    (PYTHON_DEVELOPER, 'Python Developer'),
    (RAILS_DEVELOPER, 'Rails Developer'),
    (WORDPRESS_DEVELOPER, 'Wordpress Developer'),
    (OTHER, 'Other')
    ]

    project = models.ForeignKey(
        Project, 
        on_delete=models.CASCADE,
        related_name="position"
        )
    title = models.CharField(
        max_length=3,
        choices=POSITION_CHOICES,
        )
    description = models.TextField(blank=True)
    position_filled = models.BooleanField(default=False)

    def __str__(self):
        return self.get_title_display()


class Applicant(models.Model):
    NEW = 'NEW'
    ACCEPTED = 'ACC'
    REJECTED = 'REJ'
    
    APPLICANT_CHOICES = [
    (NEW, 'New Applicant'),
    (ACCEPTED, 'Accepted'),
    (REJECTED, 'Rejected'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="applicant"
    )
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="applicant_project"
    )
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name="applicant_position"
    )
    status = models.CharField(
        max_length=3,
        choices=APPLICANT_CHOICES,
        default=NEW
    )

    def __str__(self):
        return "{} for {} project".format(self.user.profile.name, self.project)

teambuilding/projects/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Project, Position


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            'title',
            'description',
            'timeline',
            'applicant_requirements'
        ]
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'Project title',
                'class': 'circle--input--h1'
                }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Project Description',
                'rows': 5
            }),
            'timeline': forms.Textarea(attrs={
                'placeholder': 'Time Estimate',
                'class': 'circle--textarea--input',
                'rows': 5
            }),
            'applicant_requirements': forms.Textarea(attrs={
                'placeholder': 'Any additional requirements',
                'class': 'circle--textarea--input',
                'rows': 5
            })
        }
        

class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = [
            'title',
            'description',
        ]
        widgets = {
            'description': forms.Textarea(attrs={
                'placeholder': 'Position Description', 
                'rows': 5
                })
        }


PositionInlineFormSet = inlineformset_factory(
    Project,
    Position,
    form=PositionForm,
    fields=('title', 'description'),
)

teambuilding/projects/views.py
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import ProjectForm, PositionInlineFormSet
from .models import Applicant, Project, Position


class CreateProjectView(LoginRequiredMixin, CreateView):
    form_class = ProjectForm
    template_name = "projects/project_form.html"
    model = Project

    def get_context_data(self, **kwargs):
        context = super(CreateProjectView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["positions_formset"] = PositionInlineFormSet(
                self.request.POST
                )
        else:
            context["positions_formset"] = PositionInlineFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        positions = context["positions_formset"]
        with transaction.atomic():
            form.instance.project_owner = self.request.user
            self.object = form.save()
        if positions.is_valid():
            positions.instance = self.object
            positions.save()
        return super(CreateProjectView, self).form_valid(form)


class DetailProjectView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/project_detail.html"


class UpdateProjectView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = ProjectForm
    template_name = "projects/project_form.html"
    model = Project

    def test_func(self):
        obj = self.get_object()
        return obj.project_owner == self.request.user

    def get_context_data(self, **kwargs):
        context = super(UpdateProjectView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["positions_formset"] = PositionInlineFormSet(
                self.request.POST, instance=self.object
                )
        else:
            context["positions_formset"] = PositionInlineFormSet(
                instance=self.object
                )
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        positions = context["positions_formset"]
        self.object = form.save()
        if positions.is_valid():
            positions.instance = self.object
            positions.save()
        return super(UpdateProjectView, self).form_valid(form)


class DeleteProjectView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    template_name = "projects/project_delete.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        obj = self.get_object()
        return obj.project_owner == self.request.user


class ListApplicationsView(LoginRequiredMixin, ListView):
    model = Applicant
    template_name = "projects/applications.html"

    def get_queryset(self):
        filter_value = self.request.GET.get('filter', 'All Applications')
        if filter_value == 'All Applications':
            queryset = Applicant.objects.all()
        else:
            queryset = Applicant.objects.filter(
                status__icontains=filter_value[0:3]
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListApplicationsView, self).get_context_data(**kwargs)
        context['filter'] = self.request.GET.get('filter')
        return context



class CreateApplicantView(LoginRequiredMixin, CreateView):
    model = Applicant
    template_name = "projects/applicant_form.html"
    success_url = reverse_lazy("home")
    fields = ['status']

    def get_context_data(self, **kwargs):
        context = super(CreateApplicantView, self).get_context_data(**kwargs)
        context['project'] = Project.objects.get(slug=self.kwargs.get('slug'))
        context['position'] = Position.objects.get(pk=self.kwargs.get('pk'))
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        form.instance.user = self.request.user
        form.instance.project = context['project']
        form.instance.position = context['position']
        return super(CreateApplicantView, self).form_valid(form)


class UpdateApplicantView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Applicant
    template_name = "projects/applicant_edit_form.html"
    success_url = reverse_lazy("projects:applications-list")
    fields = ['status']

    def test_func(self):
        obj = self.get_object()
        return obj.project.project_owner == self.request.user

    def form_valid(self, form):
        position = self.object.position
        status = form.cleaned_data.get('status')

        if status == 'ACC':
            status = 'Congradulations! You have been accepted for the {} position.'.format(position)
            position.position_filled = True
            position.save()
        else:
            status = 'We regret to inform you that you have been rejected for the {} position.'.format(position)

        send_mail(
            self.object.project,
            status,
            self.request.user.email,
            [self.object.user.email],
            fail_silently=False,
            )
        return super(UpdateApplicantView, self).form_valid(form)

teambuilding/projects/templates/projects/applicant_edit_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds circle--page circle--article">
  <h1>Project: {{ applicant.project.title }}</h1>
  <h2>Position: {{ applicant.position }}</h2>
  <h2>{{ applicant.position.position_filled }}</h2>
  <p>Please select if you would like to accept or reject this applicant.</p>
  <div class="grid-20">
    <form action="" method="POST">
    {% csrf_token %}
      <select id="status" name="status">
        <option value="ACC">Accepted</option>
        <option value="REJ">Rejected</option>
      </select>
      <input class="button-primary" type="submit" value="Save">
    </form>
  </div>
</div>
{% endblock %}

teambuilding/projects/templates/projects/applicant_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds circle--page circle--article">
  <h1>Project: {{ project.title }}</h1>
  <h2>Position: {{ position }}</h2>
  <p>Are you sure you would like to apply for the position of {{ position }} from project {{ project.title }}?</p>
  <div class="grid-20">
    <form action="" method="POST">
    {% csrf_token %}
      {{ form.status.as_hidden }}
      <input class="button-primary" type="submit" value="Apply">
    </form>
  </div>
  <div class="grid-50">
    <a class="button" href="{% url 'projects:project-detail' slug=project.slug %}">Return</a>
  </div>
</div>
{% endblock %}

teambuilding/projects/templates/projects/applications.html
{% extends 'layout.html' %}

{% block content %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="{% url 'projects:applications-list' %}">Applications</a></li>
        <li><a href="{% url 'accounts:profile-detail' slug=user.profile.slug %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <form method="GET">
          <select name="filter">
            <option>All Applications</option>
            <option>New Applications</option>
            <option>Accepted</option>
            <option>Rejected</option>
          </select>
          <p><input type="submit" name="submit" value="submit"/></p>
        </form>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
          {% for project in user.project.all %}
            <li><a href="{% url 'projects:project-detail' slug=project.slug %}" target="_blank">{{ project }}</a></li>
          {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th>Applicant Position</th>
            <th>Applicant Status</th>
          </tr>
        </thead>
        <tbody>
        {% for applicant in object_list %}
          {% if applicant.project.project_owner == user %}
            <tr>
              <td>
                <h3><a href="{% url 'accounts:profile-detail' slug=applicant.user.profile.slug %}" target="_blank">{{ applicant.user.profile.name }}</a></h3>
                <p>{{ applicant.project }}</p>
              </td>
              <td>
                <span class="secondary-label">{{ applicant.position }}</span>
              </td>
              <td>
                <span class="secondary-label">{{ applicant.get_status_display }}</span><br><br>
                <a href="{% url 'projects:applicant-update' pk=applicant.pk %}">Edit</a>
              </td>
            </tr>
          {% endif %}
        {% endfor %}
        </tbody>
      </table>

    </div>

  </div>
{% endblock %}

teambuilding/projects/templates/projects/project_delete.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds circle--page circle--article">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="button button-primary" value="Confirm">
  </form>
</div>
{% endblock %}

teambuilding/projects/templates/projects/project_detail.html
{% extends 'layout.html' %}

{% block content %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
      {% if user == project.project_owner %}
        <a class="button" href="{% url 'projects:project-update' slug=project.slug %}">Edit Project</a>
        <a class="button button-text" href="{% url 'projects:project-delete' slug=project.slug %}">Delete Project</a>
      {% endif %}
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ project.title }}</h1>
        <p class="circle--article--byline">Project Owner: {{ project.project_owner.profile.name }} </p>
      </div>

      <div class="circle--article--body">
        <p>{{ project.description|linebreaks }}</p>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list">
        {% for position in project.position.all %}
          <li>
            <h3>{{ position }}</h3>
            <p>{{ position.description|linebreaks }}</p>
            {% if user != project.project_owner %}
              {% if position.applicant_position.all %}
                <button>Applied</button>
              {% else %}
                <a href="{% url 'projects:applicant-create' slug=project.slug pk=position.pk %}"class="button button-primary">Apply</a>
              {% endif %}
            {% endif %}
          </li>
        {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <h3>Project Needs</h3>
        <ul class="circle--link--list">
        {% for position in project.position.all %}
          <li><a>{{ position}}</a></li>
        {% endfor %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ project.timeline}}</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <p>{{ project.applicant_requirements }}</p>
      </div>

    </div>
  </div>
{% endblock %}

teambuilding/projects/templates/projects/project_form.html
{% extends 'layout.html' %}

{% block content %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <a class="button button-text" href="{% url 'home' %}">Return Home</a>
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <form method="POST">
    {% csrf_token %}
      <div class="grid-70">
        <div class="circle--article--body">
          {{ form.title }}
          {{ form.description }}
        </div>

        <div class="circle--project--positions">
          <h2>Positions</h2>
          {{ positions_formset.management_form }}
          
            <ul class="circle--group--list circle--clone--list">
              {% for position in positions_formset %}
                {{ position.id }}
                <li>
                {{ position.title }}
                {{ position.description }}
                </li>
              {% endfor %}
            </ul>
          
          <input type="submit" class="button button-primary" value="Save Project">
        </div>

      </div>
    
      <div class="grid-25 grid-push-5">

        <div class="circle--secondary--module">
          <h3>Project Timeline</h3>
          {{ form.timeline }}
        </div>

        <div class="circle--secondary--module">
          <h3>Applicant Requirements</h3>
          {{ form.applicant_requirements }}
        </div>

      </div>
    </form>
  </div>
{% endblock %}